### ISSUE TITLE
CLI hangs

### ISSUE THREAD

**Issue by janpio** [monaca/monaca-cli#148]
Tried to sign up via CLI:
![image](https://user-images.githubusercontent.com/183673/51626639-4820fc00-1f40-11e9-82da-a2714495e33e.png)

Found out via web UI I need a longer password, no change:
![image](https://user-images.githubusercontent.com/183673/51626681-638c0700-1f40-11e9-88bc-88836320d2eb.png)

Ctrl+C also doesn't let me escape the command - I have to restart my console.

**Comment by janpio** [comment]
(Your signup website also has Japanese text for the terms)

**Comment by janpio** [comment]
Ok, maybe it is not just the signup, project creation also hangs (and doesn't respond to Ctrl+C):

![image](https://user-images.githubusercontent.com/183673/51627242-c7fb9600-1f41-11e9-8e6a-b96fb7edc6c8.png)

**Comment by janpio** [comment]
Maybe it really are all the interactive commands that require some input?

![image](https://user-images.githubusercontent.com/183673/51628232-c2537f80-1f44-11e9-91c7-8b8868153e9f.png)

**Comment by suebphatt** [comment]
Could you please inform if there is any update/workaround on this issue?
I also run into this issue in the latest version of Monaca and also cannot successfully run `Monaca preview` (on Windows 10 only) 

Related? but so old >> #63

**Comment by JeremyShafer** [comment]
I have this same problem.  Frustrating!

**Comment by yong-asial** [comment]
@janpio @JeremyShafer 
The interactive commands (of project creation) are currently not supported on windows. For example, as in the suggested message, please run `monaca create --help` to see more create option i.e running `monaca create myProject --template blank` will create project with a blank template. Other interactive commands should be working properly. In addition, exiting the programming by pressing `Ctrl+C` is already fixed in the latest version `3.1.0`. Please download the latest version and try again. Also, please try using other terminals such as https://gitforwindows.org/ for better support.

**Comment by yong-asial** [comment]
@janpio @JeremyShafer
We've just able to reproduce the issue on Windows (Node: 10.x). This problem will be fixed with this PR #149. Please download the latest version `3.1.2`. Feel free to let us know if you still experience the error.
