### ISSUE TITLE
monaca create installs build dependency all the time

### ISSUE THREAD

**Issue by masahirotanaka** [monaca/monaca-cli#49]
monaca create installs build dependency all the time.
I hope it will be skipped if they are installed already.

**Comment by frandiox** [comment]
@masahirotanaka Bryan and me were talking about this issue some weeks ago. I think he preferred to let `npm` do the job due to some problems while checking dependencies versions.
I think it's possible to check the version if we include the `package.json` instead of the actual dependency while doing the check. I'll make a PR in monaca-lib repository.
