### ISSUE TITLE
Think of way to setup project from github

### ISSUE THREAD

**Issue by masahirotanaka** [monaca/monaca-cli#50]
It is a bit unsure how the user should do when using a project cloned from GitHub. Maybe it is useful if we enhance `monaca clone` to specify each repository or project, and setup dependencies based on the project configuration.

Cloning from GitHub:
 `monaca clone https://github.....`

Cloning from Monaca Cloud
`monaca clone https://monaca.mobi/projects/.....`

**Comment by frandiox** [comment]
@masahirotanaka In my opinion, maybe CLI should send the link to the backend and import the project from Github to Monaca Cloud adding necessary Monaca files to the project and then download it.
Another possibility is to do it on CLI's side but I guess it's better if the backend is the one adding Monaca files and stuff since it would be also needed when we support react/etc in Cloud IDE.
Perhaps CLI could even ask the user what type of project it is (react, angular2, etc).

**Comment by frandiox** [comment]
This has been added to `2.1.2` with `monaca create projectName --url https://github.com/profile/repo/archive/master.zip`

Only Monaca projects are importable for now.
